const cloudinary = require("cloudinary").v2;

const PROFILE_PHOTO_FOLDER = "sawaka-contributor-profiles";

let configured = false;

function ensureConfig() {
  if (configured) return;
  cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
  });
  configured = true;
}

/**
 * Stores a profile image in the existing Cloudinary account.
 * The public id is generated by Cloudinary. The client filename is never used.
 */
async function uploadProfileImage(buffer) {
  ensureConfig();
  const result = await new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      {
        folder: PROFILE_PHOTO_FOLDER,
        resource_type: "image",
        unique_filename: true,
        overwrite: false,
      },
      (err, uploaded) => (err ? reject(err) : resolve(uploaded))
    );
    stream.end(buffer);
  });

  const url = result && result.secure_url;
  const publicId = result && result.public_id;
  if (typeof url !== "string" || !url.startsWith("https://") || typeof publicId !== "string") {
    throw new Error("UPLOAD_FAILED");
  }
  return { url, publicId };
}

async function destroyStoredImage(publicId) {
  if (!publicId) return;
  ensureConfig();
  await cloudinary.uploader.destroy(publicId, { resource_type: "image" });
}

module.exports = {
  PROFILE_PHOTO_FOLDER,
  uploadProfileImage,
  destroyStoredImage,
};
